name: Fantastick
version: ${project.version}
main: me.wiviw.fantastick.Fantastick
api-version: 1.17
depend: [ NBTAPI , WorldGuard ]
authors: [ WiViW ]
description: Useful Sticks and a collection of helpful utilities.
commands:
  teleportsticks:
    description: "Grants a Teleport Stick"
  deathsticks:
    description: "Grants a Death stick"
  invistoggle:
    description: "Toggles on/off Invisibility on players"
  nightvisiontoggle:
    description: "Toggles on/off Night Vision on players"
  waterbreathingtoggle:
    description: "Toggles on/off Water Breathing on players"